version: '3'
services:

    #PHP Service
    app:
        image: php:7.4-fpm
        container_name: app
        restart: unless-stopped
        tty: true
        build:
            context: docker
            dockerfile: Dockerfile.php
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network

    #MySQL Service
    db:
        image: mysql:5.7
        container_name: db
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: your_mysql_root_password
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
            MYSQL_USER: laravel_u
            MYSQL_PASSWORD: laravel_pw
        volumes:
            - ./_docker_temp/mysql:/var/lib/mysql
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge
